// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoLudis.Data;

namespace ProjetoLudis.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjetoLudis.Models.Comerciante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPFCNPJ")
                        .HasColumnType("text");

                    b.Property<int>("IndicadorIE")
                        .HasColumnType("integer");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text");

                    b.Property<int>("Regime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Comerciantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPFCNPJ = "1222521/0001-01",
                            IndicadorIE = 0,
                            InscricaoEstadual = " ",
                            InscricaoMunicipal = " ",
                            RazaoSocial = "Clube do 100",
                            Regime = 1
                        });
                });

            modelBuilder.Entity("ProjetoLudis.Models.Esportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Esportistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "13131308670"
                        });
                });

            modelBuilder.Entity("ProjetoLudis.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<int?>("ComercianteId")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<int?>("EsportistaId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdComerciante")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEsportista")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComercianteId");

                    b.HasIndex("EsportistaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Centro",
                            CEP = "37190000",
                            Cidade = "Três Pontas",
                            Complemento = " ",
                            Email = "Iury@teste.com.br",
                            Endereco = "R. José Caixambu Nº 213",
                            IdEsportista = 1,
                            Nome = "Iury",
                            Senha = "iury123",
                            Telefone = "997288193",
                            UF = "UF"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Centro",
                            CEP = "37190000",
                            Cidade = "Três Pontas",
                            Complemento = " ",
                            Email = "           ",
                            Endereco = "R. José Caixambu Nº 213",
                            IdEsportista = 0,
                            Nome = "Iury",
                            Senha = "iury123",
                            Telefone = "997288193",
                            UF = "UF"
                        });
                });

            modelBuilder.Entity("ProjetoLudis.Models.Usuario", b =>
                {
                    b.HasOne("ProjetoLudis.Models.Comerciante", "Comerciante")
                        .WithMany()
                        .HasForeignKey("ComercianteId");

                    b.HasOne("ProjetoLudis.Models.Esportista", "Esportista")
                        .WithMany()
                        .HasForeignKey("EsportistaId");
                });
#pragma warning restore 612, 618
        }
    }
}
